### ISSUE TITLE
How should I populate the constructor of VRFCoordinatorV2Mock.sol?

### ISSUE THREAD

**Issue by Lu1z-Gust4v0** [smartcontractkit/chainlink-brownie-contracts#13]
I am trying to test the new version of the VRFCoordinator, however, in order to deploy the mock I need to pass two parameters to the constructor "baseFee" and "gasPriceLink". I couldn't find anything about how to get these values.

Here's the code of the constructor
```solidity
  constructor(uint96 _baseFee, uint96 _gasPriceLink) {
    BASE_FEE = _baseFee;
    GAS_PRICE_LINK = _gasPriceLink;
  }
```

**Comment by PatrickAlphaC** [comment]
`BASE_FEE`: Is the premium, [you can find it here.](https://docs.chain.link/docs/vrf-contracts/)
`GAS_PRICE_LINK`:  is some value set dynamically on-chain based on the price of the layer 1 (like ETH, or MATIC) and LINK

For mocking, setting the `GAS_PRICE_LINK` to something like `1e9` is probably good. If you want to make a PR to the [chainlink-mix](https://github.com/smartcontractkit/chainlink-mix) repo with what you end up doing, that would be great!

**Comment by Lu1z-Gust4v0** [comment]
Thanks for you quick response Mr. Collins.
