### ISSUE TITLE
Have git tags correspond to package versions?

### ISSUE THREAD

**Issue by gnattishness** [smartcontractkit/chainlink-brownie-contracts#2]
It would be helpful if there were git tags here that corresponded to package versions for [@chainlink/contracts](https://www.npmjs.com/package/@chainlink/contracts).

This makes it easier to port from other frameworks, and gives a better idea of the exact Chainlink code that's provided here and what we're actually depending on.

Perhaps the workflow could be triggered by new versions published to npm?

If wanting to also tag changes local to this repo perhaps using a different tag format could be helpful.
e.g. where `cl0.1.5` refers to the  @chainlink/contracts release `0.1.5`?

Thanks for your consideration.

**Comment by PatrickAlphaC** [comment]
Thank you for this issue! Sorry on my delay here. 

We are planning on depreciating this package for v0.8 of solidity, and just use the npm versions moving forward. I think you make a good point, but we won't need this repo for much longer.

**Comment by PatrickAlphaC** [comment]
Closing for now, feel free to follow up, I've turned notifications on.
