### ISSUE TITLE
Interface AggregatorV2V3Interface cannot inherit from other interfaces

### ISSUE THREAD

**Issue by y-naught** [smartcontractkit/chainlink-brownie-contracts#7]
While working with MockV3Aggregator.sol, I ran into the issue where I could not compile solidity contracts because it was importing from "smartcontractkit/chainlink-brownie-contracts/contracts/src/v0.6/interfaces/AggregatorV2V3Interface.sol".

AggregatorV2V3Interface.sol contains the line, 
interface AggregatorV2V3Interface is AggregatorInterface, AggregatorV3Interface

Which throws the error
/home/jimmyjames/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.6/interfaces/AggregatorV2V3Interface.sol:7:59: TypeError: Interfaces cannot inherit.

To solve the issue temporarily and to continue to use MockV3Aggregator in my test system, I simply replaced the middle step of importing AggregatorV2V3interface.sol by importing AggregatorInterface.sol and AggregatorV3Interface.sol independently, 

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorInterface.sol";
import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";

and inherited these two interfaces in the MockV3Aggregator contract declaration. 

contract MockV3Aggregator is AggregatorInterface, AggregatorV3Interface

**Comment by PatrickAlphaC** [comment]
Interesting... thanks for the ping here. I've seen this a few times but I havent been able to reproduce this myself. 

What's your setup look like?

**Comment by y-naught** [comment]
Here is some information about the setup I am getting errors with.

py-solc-x              1.1.1
Brownie                v1.17.1
web3                    5.24.0
Python                 3.8.10


brownie-config.yaml
Dependencies:
- smartcontractkit/chainlink-brownie-contracts@1.1.1

In the solidity contracts
pragma solidity ^0.6.0;

And here is what brownie prints when running brownie compile

Brownie v1.17.1 - Python development framework for Ethereum

New compatible solc version available: 0.6.0
Compiling contracts...
  Solc version: 0.6.0
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

/home/jimmyjames/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.6/interfaces/AggregatorV2V3Interface.sol:7:38: TypeError: Interfaces cannot inherit.
interface AggregatorV2V3Interface is AggregatorInterface, AggregatorV3Interface


Also, I tried switching everything to solidity 0.7.6 including using the v0.7 versions of the contracts in this repository and it compiled without any problems.

**Comment by PatrickAlphaC** [comment]
Can you use `smartcontractkit/chainlink-brownie-contracts@0.2.2`?

**Comment by y-naught** [comment]
That also didn't resolve the issue on it's own. 

However, I took the time to increment through solc versions and it appears that the issue persists on anything lower than solc-v0.6.1, but is resolved for solc-0.6.2 and up

Here's a screenshot of my brownie compiling for setup reference.
<img width="564" alt="Screenshot 2021-11-20 144105" src="https://user-images.githubusercontent.com/22108338/142739008-e89febbd-af49-4b42-9042-6bf547b03606.png">
.

**Comment by PatrickAlphaC** [comment]
Wild... Thanks for this note. Glad you got it solved!
