### ISSUE TITLE
LinkToken.sol version issue (ParserError: Source file requires different compiler version)

### ISSUE THREAD

**Issue by lzydaphne** [smartcontractkit/chainlink-brownie-contracts#9]
my compiler use v0.6.6, but this LinkToken.sol use pragma v0.4.11 which caused a ParserError.
How can I fix this?
![image](https://user-images.githubusercontent.com/52618403/151469104-9e7248b1-774c-4389-bb93-1363499acb90.png)

**Comment by PatrickAlphaC** [comment]
1. What version of the chainlink-brownie-contracts are you using?
2. What command are you running? 
3. Where are you using the link token?

**Comment by lzydaphne** [comment]
thanks for replying! @PatrickAlphaC 
And I managed to solve this. 
The problem is that I specified the solc version in config and forgot to delete it when trying to compile the LinkToken.sol

BTW, I'm really excited to see you planning to make a new video about solidity and js and other fun stuff🔥
